from __future__ import annotations
from .schemas import RevisionPlan, EvaluatorFeedback, HillclimbResult, GraderResult, RevisionPreferencePair

def deterministic_revision_plan(feedback: EvaluatorFeedback, target_attempt_id: str) -> RevisionPlan:
    return RevisionPlan(revision_plan_id=f'revision_plan_{feedback.task_id}', task_id=feedback.task_id, source_attempt_id=feedback.attempt_id, target_attempt_id=target_attempt_id, revision_kind='local_fix', revision_reason=feedback.feedback_summary, failed_rubric_items=feedback.failed_rubric_items, planned_changes=feedback.actionable_feedback, expected_score_improvement=0.1, risk_of_regression='low', uses_evaluator_feedback=True, metadata_json={})

def compute_hillclimb(base: GraderResult, rev: GraderResult) -> HillclimbResult:
    base_score=base.final_score if base.final_score is not None else base.score
    rev_score=rev.final_score if rev.final_score is not None else rev.score
    delta=rev_score-base_score
    if delta>0: kind='score_delta'; strength='observed_improvement'; success=True
    elif delta<0: kind='regression'; strength='regression_observed'; success=False
    elif (not base.passed) and rev.passed: kind='pass_delta'; strength='observed_improvement'; success=True
    else: kind='none'; strength='no_observed_improvement'; success=False
    improved=[c for c in base.failed_criteria if c in rev.passed_criteria]
    regressed=[c for c in base.passed_criteria if c in rev.failed_criteria]
    return HillclimbResult(hillclimb_id=f'hill_{base.task_id}', task_id=base.task_id, baseline_attempt_id=base.attempt_id, revised_attempt_id=rev.attempt_id, baseline_score=base_score, revised_score=rev_score, revision_score_delta=delta, baseline_passed=base.passed, revised_passed=rev.passed, failed_criteria_before=base.failed_criteria, failed_criteria_after=rev.failed_criteria, criteria_improved=improved, criteria_regressed=regressed, artifact_completeness_before=base.artifact_contract_score if base.artifact_contract_score is not None else base.score, artifact_completeness_after=rev.artifact_contract_score if rev.artifact_contract_score is not None else rev.score, artifact_completeness_delta=(rev.artifact_contract_score or rev.score)-(base.artifact_contract_score or base.score), regression_count=len(regressed), improvement_kind=kind, hillclimb_evidence_strength=strength, revision_success=success, metadata_json={'comparison_basis':'final_score','baseline_artifact_contract_score':base.artifact_contract_score,'revised_artifact_contract_score':rev.artifact_contract_score,'baseline_model_score':base.model_score if base.model_score is not None else base.semantic_score,'revised_model_score':rev.model_score if rev.model_score is not None else rev.semantic_score,'baseline_semantic_score':base.semantic_score,'revised_semantic_score':rev.semantic_score,'baseline_score_reliability':base.score_reliability,'revised_score_reliability':rev.score_reliability})

def preference_pair(hill: HillclimbResult, rubric_ref: str, confidence=0.8) -> RevisionPreferencePair:
    choose_rev=hill.revised_score >= hill.baseline_score
    return RevisionPreferencePair(pair_id=f'pref_{hill.task_id}', task_id=hill.task_id, rubric_ref=rubric_ref, baseline_attempt_ref=f'attempts/baseline', revised_attempt_ref=f'attempts/revised', chosen_attempt_id=hill.revised_attempt_id if choose_rev else hill.baseline_attempt_id, rejected_attempt_id=hill.baseline_attempt_id if choose_rev else hill.revised_attempt_id, baseline_score=hill.baseline_score, revised_score=hill.revised_score, score_delta=hill.revision_score_delta, criteria_improved=hill.criteria_improved, criteria_regressed=hill.criteria_regressed, preference_reason='Choose higher final_score attempt; baseline wins on regression.', score_source='final_score', grader_kind='hybrid_or_configured', confidence=confidence, metadata_json={'comparison_basis':'final_score','baseline_final_score':hill.baseline_score,'revised_final_score':hill.revised_score,'baseline_artifact_contract_score':hill.metadata_json.get('baseline_artifact_contract_score'),'revised_artifact_contract_score':hill.metadata_json.get('revised_artifact_contract_score'),'baseline_model_score':hill.metadata_json.get('baseline_model_score'),'revised_model_score':hill.metadata_json.get('revised_model_score'),'baseline_semantic_score':hill.metadata_json.get('baseline_semantic_score'),'revised_semantic_score':hill.metadata_json.get('revised_semantic_score'),'baseline_score_reliability':hill.metadata_json.get('baseline_score_reliability'),'revised_score_reliability':hill.metadata_json.get('revised_score_reliability')})
